getwd()
list.files()
data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
str(data)
subset <- subset(data[data$Date %in% c("1/2/2007","2/2/2007") ,])
str(subset)
head(subset)
day <- strptime(paste(subset$Date, subset$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
head(day)
globalActivePower <- as.numeric(subset$Global_active_power)
subMetering1 <- as.numeric(subset$Sub_metering_1)
subMetering2 <- as.numeric(subset$Sub_metering_2)
subMetering3 <- as.numeric(subset$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(day, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(day, subMetering2, type="l", col="red")
lines(day, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
