getwd()
list.files()
data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
str(data)
subset <- subset(data[data$Date %in% c("1/2/2007","2/2/2007") ,])
str(subset)
head(subset)
day <- strptime(paste(subset$Date, subset$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
head(day)
globalActivePower <- as.numeric(subset$Global_active_power)
png("plot2.png", width=480, height=480)
plot(day, globalActivePower, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()
